{
 "title": "Immich Go",
 "time": { "from": "now-24h", "to": "now" },
 "refresh": "5m",
 "panels": [
  { "title": "Row title", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 0 } },
  {
   "title": "Number of users",
   "type": "stat",
   "gridPos": { "h": 6, "w": 5, "x": 0, "y": 1 },
   "fieldConfig": { "defaults": { "unit": "string" } },
   "options": { "reduceOptions": { "calcs": [ "first" ] } },
   "targets": [
    { "expr": "immich_app_number_users", "legendFormat": "__auto" }
   ]
  },
  {
   "title": "Immich version",
   "type": "stat",
   "gridPos": { "h": 6, "w": 9, "x": 5, "y": 1 },
   "fieldConfig": { "defaults": { "unit": "string" } },
   "options": { "reduceOptions": { "calcs": [ "first" ] } },
   "targets": [
    { "expr": "immich_app_version", "legendFormat": "{{version}}" }
   ]
  },
  {
   "title": "Number of photos",
   "type": "stat",
   "gridPos": { "h": 6, "w": 5, "x": 14, "y": 1 },
   "fieldConfig": { "defaults": { "unit": "string" } },
   "options": { "reduceOptions": { "calcs": [ "first" ] } },
   "targets": [
    { "expr": "immich_app_total_photos", "legendFormat": "__auto" }
   ]
  },
  {
   "title": "Number of videos",
   "type": "stat",
   "gridPos": { "h": 6, "w": 5, "x": 19, "y": 1 },
   "fieldConfig": { "defaults": { "unit": "string" } },
   "options": { "reduceOptions": { "calcs": [ "first" ] } },
   "targets": [
    { "expr": "immich_app_total_videos", "legendFormat": "__auto" }
   ]
  },
  {
   "title": "Users details",
   "type": "table",
   "gridPos": { "h": 6, "w": 24, "x": 0, "y": 7 },
   "targets": [
    { "expr": "immich_user_info" }
   ]
  },
  {
   "title": "User usage",
   "type": "timeseries",
   "gridPos": { "h": 9, "w": 12, "x": 0, "y": 13 },
   "fieldConfig": { "defaults": { "unit": "bytes" } },
   "targets": [
    { "expr": "immich_user_usage", "legendFormat": "{{firstname}} {{lastname}}" }
   ]
  },
  {
   "title": "Total assets",
   "type": "timeseries",
   "gridPos": { "h": 9, "w": 12, "x": 12, "y": 13 },
   "targets": [
    {
     "expr": "immich_app_total_photos + immich_app_total_videos",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Proportion Photos / Videos",
   "type": "piechart",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 22 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    { "expr": "immich_app_total_photos", "legendFormat": "Photos" },
    { "expr": "immich_app_total_videos", "legendFormat": "Videos" }
   ]
  },
  {
   "title": "Usage by user",
   "type": "piechart",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 22 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    { "expr": "immich_user_usage", "legendFormat": "{{firstname}} {{lastname}}" }
   ]
  }
 ]
}